### ISSUE TITLE
Shouldn't pmiab set the DNSSEC (DS) record when it acts as the primary DNS zone server?

### ISSUE THREAD

**Issue by lifeboy** [ddavness/power-mailinabox#91]
As it is, I have change the domain's NS records at the registrar to point to pmiab and have a secondary set as well.  When I got the registrar's control panel, there are no DNS records to set, since this is delegated to pmiab.

What am I missing here please?

**Comment by lifeboy** [comment]
> Google domains here. I use glue records and normal NS in the DNS records. Worked fine. Maybe a few more details to get you the help you need.

This has little if anything to do with NS glue records, so I'm not sure I understand your response.   To add DNSSEC I need to add these records somewhere.  That somewhere should be where the zone file is, which is the pmiab machine, not the registrar.   Unless this is not so, the message on the status page of pmiab doesn't make sense.

**Comment by ddavness** [comment]
The DS records (Delegation Signature record) are added to the server that does the delegation.
The server doing the delegation to the server is the registry. Because of that, the DS record needs to be added to the registry. It works exactly the same way with MiaB.

If the DS record was published on it's own zone, it would be basically like issuing a self-signed certificate.

**Comment by lifeboy** [comment]
Ah, that makes sense.  I'll have to engage the registrar then.

Thanks for the clarification.
